name: voltzy_version_3
description: "Professional service management platform connecting homeowners with service providers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  go_router: ^13.1.0
  go_router_builder: ^2.8.0
  
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  intl: ^0.19.0
  uuid: ^4.3.3
  
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  flashy_tab_bar2: ^0.0.10
  lucide_icons: ^0.257.0

  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  analyzer: ^7.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/icons/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  remove_alpha_ios: true
